

INSERT into POSITION(id,postion) VALUES(0,'None');
INSERT into POSITION(id,postion) VALUES(1,'GoalKeeper');
INSERT into POSITION(id,postion) VALUES(1,'Defender');
INSERT into POSITION(id,postion) VALUES(1,'Midfield');
INSERT into POSITION(id,postion) VALUES(1,'Attack');
INSERT into POSITION(id,postion) VALUES(1,'Sub');

INSERT into TEAM (id,max_players,max_on_field,max_subs,team_name) VALUES (0,500,0,0,'Transfer market');

INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (1,12,'Craig Hill',0,8,5,1,5,10,0,False,5959,5066);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (2,10,'Donald Howard',0,4,2,5,8,10,0,False,6234,5662);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (3,1,'Walter Campbell',0,3,7,6,9,10,0,False,9632.3,6945);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (4,35,'Eugene Richardson',0,9,6,4,3,10,0,False,4568,4678);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (5,2,'Adam Hall',0,9,5,8,6,10,0,False,8664,9562);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (6,5,'Robert Green',0,8,5,1,5,10,0,False,7202,7564);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (7,8,'Chris Edwards',0,8,6,1,3,10,0,False,6687,6998);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (8,55,'Micheal Power',0,8,5,3,1,10,0,False,8531,8646);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (9,21,'Graham Lalor',0,4,3,4,2,10,0,False,1000,1356);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (10,22,'Eddy Ekofo',0,4,5,6,8,10,0,False,9850,9812);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (11,15,'Phillip Cheape',0,8,5,5,5,10,0,False,8995,8655);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (12,13,'Jurijs Cicelimovs',0,8,5,7,6,10,0,False,9153,8645);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (13,64,'Kenneth Perez',0,5,8,1,6,10,0,False,6135,6864);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (14,2,'Philip Simmons',0,3,3,4,9,10,0,False,7643,6443);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (15,98,'Alan Rogers',0,9,5,6,5,10,0,False,5046,5050);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (16,85,'Roger Martin',0,5,2,6,5,8,0,False,6432,6465);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (17,45,'Ryan Morgan',0,2,6,8,8,10,0,False,2249,2265);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (18,64,'Carlos Murphy',0,2,2,4,9,10,0,False,6452,4319);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (19,19,'Johnny Sanders',0,8,5,1,5,10,0,False,5959,5066);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (20,35,'Charles Hughes',0,8,2,3,3,10,0,False,5999,5662);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (21,7,'David Barnes',0,4,4,6,9,10,0,False,5219,5846);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (22,9,'Eric Gray',0,8,6,7,9,10,0,False,5649,5946);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (23,36,'Brandon Roberts',0,3,7,5,6,10,0,False,5222,2016);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (24,22,'Jeremy Bailey',0,6,3,4,5,10,0,False,2265,2253);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (25,92,'Dnnis Butler',0,5,2,9,4,10,0,False,4561,3135);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (26,46,'George Parker',0,8,5,4,5,10,0,False,6456,2254);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (27,91,'Joe Sanchez',0,4,5,9,5,10,0,False,5959,5066);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (28,53,'William Young',0,6,5,8,5,10,0,False,5569,5796);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (29,47,'Todd Walker',0,8,5,5,7,10,0,False,9559,5466);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (30,30,'Willie Baker',0,4,5,6,5,10,0,False,4545,6546);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (31,29,'Daniel Cox',0,6,5,1,3,10,0,False,5365,5946);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (32,34,'James Robinson',0,9,5,1,5,10,0,False,6666,4689);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (33,28,'Scott Collins',0,6,5,7,5,10,0,False,4384,4683);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (34,4,'Christopher Bennett',0,5,5,6,5,10,0,False,5565,5066);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (35,16,'Howard Watson',0,8,8,1,5,10,0,False,8975,9213);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (36,41,'Matthew King',0,5,3,6,8,10,0,False,4623,4568);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (37,42,'Matthew Thompson',0,4,5,1,8,10,0,False,5339,3456);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (38,48,'Conor Griffin',0,2,4,3,6,10,0,False,1358,1356);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (39,52,'Keith Long',0,8,5,1,5,10,0,False,4563,7896);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (40,56,'Gary Lee',0,8,3,8,5,10,0,False,5559,5866);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (49,37,'Jeffrey Carter',0,7,5,6,5,10,0,False,3546,5631);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (50,38,'Joshua Price',0,8,5,4,5,10,0,False,2301,4643);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (51,18,'Simon Harris',0,6,5,5,2,10,0,False,8959,5316);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (52,73,'Clarence Peterson',0,3,5,5,6,10,0,False,1356,5449);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (53,61,'Gregory Bryant',0,5,3,1,8,10,0,False,6959,6566);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (54,71,'Douglas Ward',0,7,5,4,5,10,0,False,6799,6896);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (55,81,'Thomas Wood',0,6,5,4,5,10,0,False,7945,3546);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (56,91,'Earl Lopez',0,4,5,1,5,10,0,False,2135,2304);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (57,95,'Peter Jackson',0,1,5,1,10,10,0,False,6959,7966);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (58,45,'Jason Coleman',0,8,5,8,5,10,0,False,5461,7631);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (59,63,'Larry Mitchell',0,7,5,1,5,10,0,False,5879,5864);
INSERT into PLAYER (id,jersey_num,player_name,position_id,att_val,def_val,mid_val,gk_val,health,team_id_team_id,injury,salary,transfer_value) VALUES (60,72,'Lee Healey',0,6,8,3,4,10,0,False,6431,4315);
